name: snorkel
channels:
  - conda-forge
  - pytorch
dependencies:
  - beautifulsoup4==4.7.1
  - future==0.17.1
  - ipywidgets==7.4.2
  - jupyter==1.0.0
  - lxml==4.3.3
  - matplotlib==3.0.1
  - nltk==3.2.5
  - numba==0.43.1
  - numpy==1.16.1
  - pytorch==1.1.0
  - pandas==0.24.2
  - py4j==0.10.8.1
  - python>=3.6
  - requests==2.22.0
  - runipy==0.1.5
  - scipy==1.2.1
  - six==1.12.0
  - spacy==1.9.0
  - sqlalchemy==1.3.3
  - tika==1.19
  - tqdm==4.32.1
  - pip:
    - git+https://github.com/HazyResearch/numbskull@master
    - git+https://github.com/HazyResearch/treedlib@master
